"""
Code Writer + Debugger + Documentation Agent
Using LangChain, LangGraph, and Groq API

Flow:
  User Prompt → Generate Code → Execute Code → Debug (loop) → Document + Save Code
"""
#WRITEDEDOC


import os
import sys
import re
import io
import contextlib
from datetime import datetime
from typing import TypedDict
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, END

load_dotenv()

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise ValueError("❌  GROQ_API_KEY not found. Set it in your .env file.")

MODEL_NAME         = "llama-3.1-8b-instant"   # fast & capable on Groq
MAX_DEBUG_ITERATIONS = 5
OUTPUT_DIR         = "output"                  # all artefacts land here


# ─────────────────────────────────────────────
# TOOL 1 — Python REPL  (executes code locally)
# ─────────────────────────────────────────────
def python_repl_tool(code: str) -> dict:
    """
    Execute Python code in a sandboxed local namespace.

    Parameters
    ----------
    code : str
        Valid Python source code to execute.

    Returns
    -------
    dict
        {
          "stdout"  : str,   # anything printed to stdout
          "stderr"  : str,   # exception message (empty on success)
          "success" : bool   # True when no exception was raised
        }
    """
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    namespace  = {}

    try:
        with contextlib.redirect_stdout(stdout_buf), \
             contextlib.redirect_stderr(stderr_buf):
            exec(compile(code, "<agent_code>", "exec"), namespace)
        return {
            "stdout":  stdout_buf.getvalue(),
            "stderr":  stderr_buf.getvalue(),
            "success": True,
        }
    except Exception as exc:
        return {
            "stdout":  stdout_buf.getvalue(),
            "stderr":  f"{type(exc).__name__}: {exc}",
            "success": False,
        }


# ─────────────────────────────────────────────
# TOOL 2a — Code File Writer
# ─────────────────────────────────────────────
def code_writer_tool(code: str, filename: str = "final_code.py") -> str:
    """
    Write the verified Python code to output/<filename>.

    Parameters
    ----------
    code     : str   Final working Python source.
    filename : str   Target filename inside OUTPUT_DIR.

    Returns
    -------
    str   Absolute path of the written file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, filename)
    header = (
        f'"""\nAuto-generated by Code-Writer Agent\n'
        f'Timestamp : {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n"""\n\n'
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + code)
    return path


# ─────────────────────────────────────────────
# TOOL 2b — Documentation Writer
# ─────────────────────────────────────────────
def documentation_tool(raw_doc: str, filename: str = "documentation.md") -> str:
    """
    Write Markdown documentation to output/<filename>.

    Parameters
    ----------
    raw_doc  : str   Full Markdown text produced by the LLM.
    filename : str   Target filename inside OUTPUT_DIR.

    Returns
    -------
    str   Absolute path of the written file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(raw_doc)
    return path


# ─────────────────────────────────────────────
# LLM CLIENT (Groq)
# ─────────────────────────────────────────────
llm = ChatGroq(api_key=GROQ_API_KEY, model=MODEL_NAME, temperature=0.2)


def call_llm(messages: list) -> str:
    """Call Groq LLM and return the plain-text response."""
    response = llm.invoke(messages)
    return response.content


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────
def extract_code(text: str) -> str:
    """Pull the first ```python … ``` block from LLM output."""
    pattern = r"```(?:python)?\s*(.*?)```"
    match   = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()   # fallback: raw text


def log(step: str, message: str):
    """Pretty-print a ReAct-style log line."""
    icons = {
        "Thought":     "💭",
        "Action":      "⚡",
        "Observation": "👁️ ",
        "Final":       "✅",
        "Error":       "❌",
    }
    icon = icons.get(step, "•")
    print(f"\n{'─'*60}")
    print(f"{icon}  [{step}]")
    print(message)
    print("─"*60)


# ─────────────────────────────────────────────
# GRAPH STATE
# ─────────────────────────────────────────────
class AgentState(TypedDict):
    user_prompt:      str    # original user task
    current_code:     str    # latest generated / fixed code
    execution_result: dict   # output from python_repl_tool
    iteration:        int    # debug-loop counter
    final_code:       str    # confirmed-working code
    documentation:    str    # generated markdown docs
    status:           str    # "executing" | "debugging" | "done" | "failed"


# ─────────────────────────────────────────────
# NODE 1 — Generate initial code
# ─────────────────────────────────────────────
def generate_code_node(state: AgentState) -> AgentState:
    log("Thought", (
        f"User wants: {state['user_prompt']}\n"
        "I will generate clean, well-documented Python code for this task."
    ))

    system = SystemMessage(content=(
        "You are an expert Python developer. "
        "When asked to write code, output ONLY a single ```python ... ``` block. "
        "No explanations outside the block."
    ))
    human = HumanMessage(content=(
        f"Write Python code for the following task:\n\n{state['user_prompt']}\n\n"
        "Requirements:\n"
        "- Include docstrings on every function\n"
        "- Handle edge cases (empty input, wrong types, etc.)\n"
        "- Add a small demo / test at the bottom inside `if __name__ == '__main__':`"
    ))

    log("Action", "Calling LLM (Groq) → generate initial code")
    raw  = call_llm([system, human])
    code = extract_code(raw)

    log("Observation", f"Generated code:\n\n{code}")

    return {
        **state,
        "current_code": code,
        "iteration":    0,
        "status":       "executing",
    }


# ─────────────────────────────────────────────
# NODE 2 — Execute code with TOOL 1
# ─────────────────────────────────────────────
def execute_code_node(state: AgentState) -> AgentState:
    log("Action", (
        f"[TOOL: python_repl_tool] Executing code "
        f"(attempt {state['iteration'] + 1})"
    ))

    result = python_repl_tool(state["current_code"])

    obs = (
        f"Success : {result['success']}\n"
        f"STDOUT  :\n{result['stdout'] or '(empty)'}\n"
        f"STDERR  :\n{result['stderr'] or '(none)'}"
    )
    log("Observation", obs)

    new_status = "done" if result["success"] else "debugging"
    return {**state, "execution_result": result, "status": new_status}


# ─────────────────────────────────────────────
# NODE 3 — Debug / fix code (loop)
# ─────────────────────────────────────────────
def debug_code_node(state: AgentState) -> AgentState:
    iteration = state["iteration"] + 1

    if iteration > MAX_DEBUG_ITERATIONS:
        log("Error", (
            f"Exceeded max debug iterations ({MAX_DEBUG_ITERATIONS}). "
            "Stopping."
        ))
        return {**state, "iteration": iteration, "status": "failed"}

    error_msg = state["execution_result"].get("stderr", "Unknown error")
    log("Thought", (
        f"Iteration {iteration}: The code produced an error.\n"
        f"Error  : {error_msg}\n"
        "I will analyse the error and produce a corrected version."
    ))

    system = SystemMessage(content=(
        "You are an expert Python debugger. "
        "Fix the broken code and output ONLY a single ```python ... ``` block. "
        "No explanations outside the block."
    ))
    human = HumanMessage(content=(
        f"Original task:\n{state['user_prompt']}\n\n"
        f"Broken code:\n```python\n{state['current_code']}\n```\n\n"
        f"Error message:\n{error_msg}\n\n"
        "Fix the error. Return the COMPLETE corrected code (not just the diff)."
    ))

    log("Action", f"Calling LLM (Groq) → fix error (attempt {iteration})")
    raw        = call_llm([system, human])
    fixed_code = extract_code(raw)

    log("Observation", f"Fixed code:\n\n{fixed_code}")

    return {
        **state,
        "current_code": fixed_code,
        "iteration":    iteration,
        "status":       "executing",
    }


# ─────────────────────────────────────────────
# NODE 4 — Save code + generate documentation
# ─────────────────────────────────────────────
def generate_docs_node(state: AgentState) -> AgentState:
    log("Thought", (
        "Code is verified and working. "
        "Saving final code to file, then generating structured Markdown documentation."
    ))

    # ── Save final code with TOOL 2a ──────────
    log("Action", "[TOOL: code_writer_tool] Writing final_code.py to disk")
    code_path = code_writer_tool(state["current_code"])
    log("Observation", f"Final code saved → {code_path}")

    # ── Generate rich documentation ───────────
    timestamp   = datetime.now().strftime("%Y-%m-%d")
    debug_iters = state["iteration"]

    system = SystemMessage(content=(
        "You are a senior technical writer specialising in Python open-source projects. "
        "Produce clear, professional, and visually well-structured Markdown documentation. "
        "Use tables, code fences, and callout blocks (> ⚠️ …) where appropriate."
    ))
    human = HumanMessage(content=(
        f"**Original task (context):**\n{state['user_prompt']}\n\n"
        f"**Final verified Python code:**\n```python\n{state['current_code']}\n```\n\n"
        f"**Agent metadata:**\n"
        f"- Model used     : {MODEL_NAME}\n"
        f"- Debug iterations required: {debug_iters}\n"
        f"- Generated on   : {timestamp}\n\n"
        "Generate a comprehensive Markdown documentation file with **exactly** these sections "
        "(use the headings verbatim):\n\n"
        "## 📌 Overview\n"
        "A short paragraph explaining what this code does and the problem it solves.\n\n"
        "## 🔍 How It Works\n"
        "A numbered step-by-step walkthrough of the logic (no code, just plain English).\n\n"
        "## 📦 Function Reference\n"
        "For EVERY function in the code, produce a sub-section with:\n"
        "- **Signature** (in a code fence)\n"
        "- **Description** (what it does)\n"
        "- **Parameters** (Markdown table: Name | Type | Description | Default)\n"
        "- **Returns** (Markdown table: Type | Description)\n"
        "- **Raises** (list any exceptions)\n\n"
        "## 💡 Example Usage\n"
        "Show 2–3 realistic usage examples with expected output (use code fences).\n\n"
        "## ⚠️ Edge Cases Handled\n"
        "Bullet list of every edge case the code guards against.\n\n"
        "## 🚀 Quick Start\n"
        "Exact commands to install dependencies and run the file:\n"
        "```bash\npip install -r requirements.txt\npython output/final_code.py\n```\n\n"
        "## 📋 Dependencies\n"
        "A Markdown table listing every import: Module | Version | Purpose.\n\n"
        "## 🛠️ Agent Execution Log Summary\n"
        f"A short paragraph noting the model ({MODEL_NAME}), "
        f"how many debug iterations were needed ({debug_iters}), "
        f"and the generation date ({timestamp}).\n\n"
        "## 📝 Changelog\n"
        f"| Version | Date | Notes |\n"
        f"|---------|------|-------|\n"
        f"| 1.0.0   | {timestamp} | Initial auto-generated version |\n"
    ))

    log("Action", "Calling LLM (Groq) → generate rich documentation")
    raw_doc = call_llm([system, human])

    # Prepend a top-level title + badge strip the LLM won't know to add
    badge_block = (
        f"# 📚 Documentation\n\n"
        f"> **Auto-generated** by the Code-Writer + Debugger Agent  \n"
        f"> Model: `{MODEL_NAME}` &nbsp;|&nbsp; "
        f"Generated: `{timestamp}` &nbsp;|&nbsp; "
        f"Debug iterations: `{debug_iters}`\n\n"
        f"---\n\n"
    )
    full_doc = badge_block + raw_doc

    # ── Save documentation with TOOL 2b ───────
    log("Action", "[TOOL: documentation_tool] Writing documentation.md to disk")
    doc_path = documentation_tool(full_doc)
    log("Observation", f"Documentation saved → {doc_path}")

    log("Final", (
        "Agent completed successfully!\n"
        f"  • Final code    → {code_path}\n"
        f"  • Documentation → {doc_path}"
    ))

    return {
        **state,
        "final_code":    state["current_code"],
        "documentation": full_doc,
        "status":        "done",
    }


# ─────────────────────────────────────────────
# ROUTER — decides the next node
# ─────────────────────────────────────────────
def route(state: AgentState) -> str:
    status = state["status"]
    if status == "executing":
        return "execute_code"
    if status == "debugging":
        return "debug_code"
    if status == "done":
        return "generate_docs"
    return END   # "failed" or unknown → stop


# ─────────────────────────────────────────────
# BUILD THE LANGGRAPH
# ─────────────────────────────────────────────
def build_graph():
    g = StateGraph(AgentState)

    g.add_node("generate_code", generate_code_node)
    g.add_node("execute_code",  execute_code_node)
    g.add_node("debug_code",    debug_code_node)
    g.add_node("generate_docs", generate_docs_node)

    g.set_entry_point("generate_code")

    # generate_code → always execute first
    g.add_edge("generate_code", "execute_code")

    # execute_code → route on success / failure
    g.add_conditional_edges(
        "execute_code",
        route,
        {
            "debug_code":    "debug_code",
            "generate_docs": "generate_docs",
            END:              END,
        },
    )

    # debug_code → re-execute or give up
    g.add_conditional_edges(
        "debug_code",
        route,
        {
            "execute_code": "execute_code",
            END:             END,
        },
    )

    # generate_docs → always end
    g.add_edge("generate_docs", END)

    return g.compile()


# ─────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────
def run_agent(user_prompt: str):
    print("\n" + "═"*60)
    print("  CODE WRITER + DEBUGGER + DOCUMENTATION AGENT")
    print("  Powered by Groq + LangGraph")
    print("═"*60)
    print(f"\n📝  Task: {user_prompt}\n")

    graph = build_graph()

    initial_state: AgentState = {
        "user_prompt":      user_prompt,
        "current_code":     "",
        "execution_result": {},
        "iteration":        0,
        "final_code":       "",
        "documentation":    "",
        "status":           "executing",
    }

    final_state = graph.invoke(initial_state)

    # ── Print final code ──────────────────────
    print("\n" + "═"*60)
    print(f"  FINAL WORKING CODE  (saved → {OUTPUT_DIR}/final_code.py)")
    print("═"*60)
    print(final_state.get("final_code", "⚠️  No working code produced."))

    # ── Print doc preview ────────────────────
    print("\n" + "═"*60)
    print(f"  DOCUMENTATION PREVIEW  (full version → {OUTPUT_DIR}/documentation.md)")
    print("═"*60)
    doc = final_state.get("documentation", "")
    print(doc[:800] + ("…\n[truncated — see documentation.md]" if len(doc) > 800 else ""))

    return final_state


if __name__ == "__main__":
    prompt = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else (
        "Write a Python function that takes a list of numbers and returns "
        "the mean, median, and mode. Handle edge cases like an empty list "
        "and multiple modes."
    )
    run_agent(prompt)