"""
Auto-generated by Code-Writer Agent
Timestamp : 2026-04-02 12:56:03
"""

def is_armstrong(n: int) -> bool:
    """
    Checks if a number is an Armstrong number.

    An Armstrong number is a number that is equal to the sum of cubes of its digits.

    Args:
        n (int): The number to check.

    Returns:
        bool: True if the number is an Armstrong number, False otherwise.
    """
    if not isinstance(n, int):
        raise TypeError("Input must be an integer.")
    if n < 0:
        raise ValueError("Input must be a non-negative integer.")
    return n == sum(int(digit) ** len(str(n)) for digit in str(n))


def is_happy(n: int) -> bool:
    """
    Checks if a number is a happy number.

    A happy number is a number defined by the following process: Starting with any positive integer, replace the number by the sum of the squares of its digits, and repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.

    Args:
        n (int): The number to check.

    Returns:
        bool: True if the number is a happy number, False otherwise.
    """
    if not isinstance(n, int):
        raise TypeError("Input must be an integer.")
    if n < 1:
        raise ValueError("Input must be a positive integer.")
    seen = set()
    while n != 1 and n not in seen:
        seen.add(n)
        n = sum(int(digit) ** 2 for digit in str(n))
    return n == 1


def print_armstrong_happy_numbers(n: int) -> None:
    """
    Prints all Armstrong numbers which are also happy numbers up to n.

    Args:
        n (int): The upper limit.

    Returns:
        None
    """
    if not isinstance(n, int):
        raise TypeError("Input must be an integer.")
    if n < 1:
        raise ValueError("Input must be a positive integer.")
    for i in range(1, n + 1):
        if is_armstrong(i) and is_happy(i):
            print(i)


if __name__ == '__main__':
    print_armstrong_happy_numbers(1000)
